### ISSUE TITLE
Namespacing Syntax on Concerns::Findable

### ISSUE THREAD

**Issue by tgray017** [learn-co-curriculum/ruby-music-library-cli#50] opened 2018-11-21 17:04 UTC
Hello,

I was getting an uninitialized constant error using the following convention for the Concerns::Findable module laid out in the instructions:
```
module Concerns::ModuleName
    # Module code here
end
```
Here is a sample of the error message:
```
// ♥ learn --fail-fast
/home/redolent-teacher-2456/ruby-music-library-cli-v-000/lib/artist.rb:9:in `<class:Artist>': uninitialized constant Artist::Concerns (NameError)
        from /home/redolent-teacher-2456/ruby-music-library-cli-v-000/lib/artist.rb:8:in `<top (required)>'
```
However I looked back to the Intro to Modules lab and the convention for nested modules there was the following:
```
module Concerns
    module ModuleName
        #Module code here
    end
end
```
I adjusted my code to reflect the above and I was no longer receiving that error. Are the instructions inaccurate or am I misunderstanding the instructions?

Feel free to take a look at the lib/concerns/findable.rb file in my repo for this project here: https://github.com/tgray017/ruby-music-library-cli-v-000/blob/master/lib/concerns/findable.rb

After completing this lab, I tested it one more time and swapped out this convention:
```
module Concerns
  module Findable
    def find_by_name(name)
      self.all.detect {|object| object.name == name}
    end
    
    def find_or_create_by_name(name)
      if self.find_by_name(name).nil?
        self.create(name)
      else
        self.find_by_name(name)
      end
    end
  end
end
```
with this convention:
```
module Concerns::Findable
    def find_by_name(name)
      self.all.detect {|object| object.name == name}
    end
    
    def find_or_create_by_name(name)
      if self.find_by_name(name).nil?
        self.create(name)
      else
        self.find_by_name(name)
      end
    end
end
```
and again received the error.

**Comment by maxwellbenton** [comment] 2018-11-26 16:05
Hi there @tgray017,

I've taken a look at this lesson's tests and solution and took a look at your code, but I was unable to reproduce the error, as both conventions work and pass all tests. Based on the error you posted, `uninitialized constant Artist::Concerns (NameError)` suggests that the line `extend Artist::Concerns` was present in the Artist class, rather than the correct `extend Concerns::Findable`.

I'm going to close this issue, but if you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed as completed by maxwellbenton** 2018-11-26 16:05 UTC
Labels: Test

**Comment by tgray017** [comment] 2018-11-26 22:17
@maxwellbenton feel free to take a look at my artist.rb file in my repo here: https://github.com/tgray017/ruby-music-library-cli-v-000/blob/master/lib/artist.rb. You can see I'm extending `Concerns::Findable`. I'm using the IDE, and at the very end of the lab, after all tests passed, I swapped the two different namespacing conventions and only got an error using the `module Concerns::Findable` convention, so I'm not sure what the issue was.
